from backend.clases.agenda_turno import AgendaTurno
from backend.clases.enfermedad import Enfermedad
from backend.clases.especialidad import Especialidad
from backend.clases.estado_turno import EstadoTurno
from backend.clases.historial_clinico import HistorialClinico
from backend.clases.historial_enfermedad import HistorialEnfermedad
from backend.clases.medico import Medico
from backend.clases.paciente import Paciente
from backend.clases.receta import Receta
from backend.clases.tipo_usuario import TipoUsuario
from backend.clases.usuario import Usuario
from backend.clases.visita import Visita
